version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi-devtools
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis服务配置
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: D:\Docker\data\database




