version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /d/Python/fastapi-devtools/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /d/Python/fastapi-devtools/docker/nginx/conf:/etc/nginx/conf.d
      - /d/Python/fastapi-devtools/docker/nginx/html:/usr/share/nginx/html
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
